kind: Service
apiVersion: v1
metadata:
  name: chat
  labels:
    app: chat
spec:
  type: NodePort
  selector:
    app: chat
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
        version: v1
    spec:
      containers:
      - name: chat
        image: chat
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
