security:
  enabled: false
llm:
  path: /Users/srusen/Library/Application Support/nomic.ai/GPT4All/nous-hermes-13b.ggmlv3.q4_0.bin
  npredict: 4096
  temp: 0.28
  topk: 40
  topp: 0.95
  debug: false

server:
  port: 8080
  host: 0.0.0.0

cors:
  enabled: true
  paths:
    - path-pattern: /*
      allow-origins: [ "*" ]
      allow-methods: [ "*" ]
      allow-headers: [ "*" ]
      allow-credentials: true
      max-age: -1